"""
Shared pytest fixtures for pyMDMix tests.
"""

import pytest
import numpy as np
from pathlib import Path
import tempfile
import shutil


@pytest.fixture
def tmp_output_dir():
    """Temporary directory for test outputs."""
    path = Path(tempfile.mkdtemp(prefix="pymdmix_test_"))
    yield path
    shutil.rmtree(path, ignore_errors=True)


@pytest.fixture
def sample_coordinates():
    """Sample atomic coordinates for testing."""
    # Small protein-like coordinates (100 atoms)
    np.random.seed(42)
    coords = np.random.randn(100, 3) * 10  # ~10 Angstrom spread
    coords += np.array([25, 25, 25])  # Center around (25, 25, 25)
    return coords.astype(np.float64)


@pytest.fixture
def sample_trajectory_coords():
    """Sample trajectory coordinates (10 frames, 100 atoms)."""
    np.random.seed(42)
    n_frames = 10
    n_atoms = 100
    
    # Base coordinates
    base = np.random.randn(n_atoms, 3) * 10
    base += np.array([25, 25, 25])
    
    # Add small perturbations for each frame
    frames = []
    for i in range(n_frames):
        perturbation = np.random.randn(n_atoms, 3) * 0.5
        frames.append((base + perturbation).astype(np.float64))
    
    return frames


@pytest.fixture
def sample_pdb_content():
    """Sample PDB file content."""
    return """ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00           N
ATOM      2  CA  ALA A   1       1.458   0.000   0.000  1.00  0.00           C
ATOM      3  C   ALA A   1       2.009   1.420   0.000  1.00  0.00           C
ATOM      4  O   ALA A   1       1.246   2.390   0.000  1.00  0.00           O
ATOM      5  CB  ALA A   1       1.986  -0.760  -1.216  1.00  0.00           C
ATOM      6  N   GLY A   2       3.326   1.544   0.000  1.00  0.00           N
ATOM      7  CA  GLY A   2       3.941   2.861   0.000  1.00  0.00           C
ATOM      8  C   GLY A   2       5.457   2.779   0.000  1.00  0.00           C
ATOM      9  O   GLY A   2       6.030   1.689   0.000  1.00  0.00           O
ATOM     10  OXT GLY A   2       6.073   3.848   0.000  1.00  0.00           O
TER
HETATM   11  O   WAT A   3      10.000  10.000  10.000  1.00  0.00           O
HETATM   12  H1  WAT A   3      10.757  10.000  10.586  1.00  0.00           H
HETATM   13  H2  WAT A   3       9.243  10.000  10.586  1.00  0.00           H
END
"""


@pytest.fixture
def sample_pdb_file(tmp_output_dir, sample_pdb_content):
    """Sample PDB file."""
    pdb_path = tmp_output_dir / "sample.pdb"
    pdb_path.write_text(sample_pdb_content)
    return pdb_path


@pytest.fixture
def sample_dx_content():
    """Sample DX file content (3x3x3 grid)."""
    return """# OpenDX density grid
# Generated by pyMDMix
object 1 class gridpositions counts 3 3 3
origin 0.000000 0.000000 0.000000
delta 1.000000 0.000000 0.000000
delta 0.000000 1.000000 0.000000
delta 0.000000 0.000000 1.000000
object 2 class gridconnections counts 3 3 3
object 3 class array type double rank 0 items 27 data follows
1.000000e+00 2.000000e+00 3.000000e+00
4.000000e+00 5.000000e+00 6.000000e+00
7.000000e+00 8.000000e+00 9.000000e+00
1.000000e+01 1.100000e+01 1.200000e+01
1.300000e+01 1.400000e+01 1.500000e+01
1.600000e+01 1.700000e+01 1.800000e+01
1.900000e+01 2.000000e+01 2.100000e+01
2.200000e+01 2.300000e+01 2.400000e+01
2.500000e+01 2.600000e+01 2.700000e+01
attribute "dep" string "positions"
object "density" class field
component "positions" value 1
component "connections" value 2
component "data" value 3
"""


@pytest.fixture
def sample_dx_file(tmp_output_dir, sample_dx_content):
    """Sample DX file."""
    dx_path = tmp_output_dir / "sample.dx"
    dx_path.write_text(sample_dx_content)
    return dx_path


class MockTrajectoryReader:
    """Mock trajectory reader for testing without real files."""
    
    def __init__(self, frames: list[np.ndarray]):
        self._frames = frames
        self._n_atoms = frames[0].shape[0] if frames else 0
    
    @property
    def n_frames(self) -> int:
        return len(self._frames)
    
    @property
    def n_atoms(self) -> int:
        return self._n_atoms
    
    def __len__(self) -> int:
        return self.n_frames
    
    def __iter__(self):
        from pymdmix.core.trajectory import Frame
        for coords in self._frames:
            yield Frame(coordinates=coords)


@pytest.fixture
def mock_trajectory(sample_trajectory_coords):
    """Mock trajectory reader with sample coordinates."""
    return MockTrajectoryReader(sample_trajectory_coords)
