"""
NAMD Engine Interface
=====================

Generate NAMD configuration files for MDMix workflows.

Examples
--------
>>> from pymdmix.engines.namd import NAMDEngine
>>> engine = NAMDEngine()
>>> engine.write_minimization("system.prmtop", "system.inpcrd", "min.namd")
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import numpy as np

log = logging.getLogger(__name__)


@dataclass
class NAMDConfig:
    """
    NAMD simulation configuration.
    
    Attributes
    ----------
    cutoff : float
        Nonbonded cutoff in Angstroms
    switch_dist : float
        Switching distance in Angstroms
    pairlist_dist : float
        Pairlist distance in Angstroms
    timestep : float
        Integration timestep in femtoseconds
    temperature : float
        Temperature in Kelvin
    pressure : float
        Pressure in bar (for NPT)
    langevin_damping : float
        Langevin damping coefficient in 1/ps
    """
    cutoff: float = 9.0
    switch_dist: float = 7.5
    pairlist_dist: float = 13.5
    timestep: float = 2.0
    temperature: float = 300.0
    pressure: float = 1.01325
    langevin_damping: float = 1.0
    
    # PME settings
    pme_grid_spacing: float = 1.0
    
    # Restraint settings
    restraint_weight: float = 10.0  # kcal/mol/Å²
    restraint_mask: str | None = None


class NAMDEngine:
    """
    NAMD simulation engine for MDMix.
    
    Generates NAMD configuration files for running simulations
    with Amber topology files.
    """
    
    def __init__(self, config: NAMDConfig | None = None):
        self.config = config or NAMDConfig()
        self.log = logging.getLogger(self.__class__.__name__)
    
    def _get_box_from_inpcrd(self, inpcrd_path: Path) -> tuple[float, float, float]:
        """Read box dimensions from Amber inpcrd file."""
        with open(inpcrd_path) as f:
            lines = f.readlines()
        
        # Box is in last line for periodic systems
        box_line = lines[-1].strip()
        parts = box_line.split()
        
        if len(parts) >= 3:
            try:
                return (float(parts[0]), float(parts[1]), float(parts[2]))
            except ValueError:
                pass
        
        # Default box if not found
        return (50.0, 50.0, 50.0)
    
    def _get_common_config(self, topology: Path, coordinates: Path, box: tuple) -> str:
        """Generate common NAMD configuration section."""
        return f'''# NAMD Configuration - Generated by pyMDMix
# Force field
amber                   on
parmfile                {topology}
ambercoor               {coordinates}
readexclusions          yes
exclude                 scaled1-4
1-4scaling              0.833333

# Periodic boundary conditions
cellBasisVector1        {box[0]:.3f} 0.0 0.0
cellBasisVector2        0.0 {box[1]:.3f} 0.0
cellBasisVector3        0.0 0.0 {box[2]:.3f}
cellOrigin              {box[0]/2:.3f} {box[1]/2:.3f} {box[2]/2:.3f}

wrapAll                 on
wrapNearest             on

# Nonbonded
cutoff                  {self.config.cutoff}
switching               on
switchdist              {self.config.switch_dist}
pairlistdist            {self.config.pairlist_dist}

# PME
PME                     on
PMEGridSpacing          {self.config.pme_grid_spacing}

# Rigid bonds
rigidBonds              all
rigidTolerance          0.00001

# Timestep
timestep                {self.config.timestep}
'''
    
    def _get_restraint_config(self, pdb_path: str) -> str:
        """Generate restraint configuration."""
        return f'''
# Restraints
constraints             on
consref                 {pdb_path}
conskfile               {pdb_path}
conskcol                B
constraintScaling       {self.config.restraint_weight}
'''
    
    def write_minimization(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 5000,
        restraint_pdb: str | None = None,
    ) -> Path:
        """
        Write NAMD minimization configuration.
        
        Parameters
        ----------
        topology : Path
            Amber topology file (.prmtop)
        coordinates : Path
            Amber coordinates file (.inpcrd)
        output : Path
            Output NAMD config file path
        steps : int
            Number of minimization steps
        restraint_pdb : str, optional
            PDB file with restraint forces in B-factor column
            
        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)
        
        box = self._get_box_from_inpcrd(coordinates)
        
        restraint_section = ""
        if restraint_pdb:
            restraint_section = self._get_restraint_config(restraint_pdb)
        
        config = f'''{self._get_common_config(topology, coordinates, box)}
# Output
outputname              {output.stem}
outputEnergies          100
restartfreq             1000
DCDfreq                 0

# Minimization
minimization            on
minimize                {steps}
{restraint_section}
'''
        
        output.write_text(config)
        self.log.info(f"Wrote minimization config: {output}")
        return output
    
    def write_heating(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 50000,
        start_temp: float = 0.0,
        target_temp: float | None = None,
        restraint_pdb: str | None = None,
    ) -> Path:
        """
        Write NAMD heating/equilibration configuration.
        
        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Input coordinates (restart from minimization)
        output : Path
            Output NAMD config file path
        steps : int
            Number of equilibration steps
        start_temp : float
            Starting temperature in K
        target_temp : float, optional
            Target temperature (defaults to config.temperature)
        restraint_pdb : str, optional
            PDB file with restraint forces
            
        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)
        
        target_temp = target_temp or self.config.temperature
        box = self._get_box_from_inpcrd(coordinates)
        
        restraint_section = ""
        if restraint_pdb:
            restraint_section = self._get_restraint_config(restraint_pdb)
        
        # Calculate temperature increment
        reassign_freq = 100
        n_reassigns = steps // reassign_freq
        temp_incr = (target_temp - start_temp) / max(n_reassigns, 1)
        
        config = f'''{self._get_common_config(topology, coordinates, box)}
# Input
bincoordinates          {output.stem.replace('_heat', '_min')}.coor
binvelocities           {output.stem.replace('_heat', '_min')}.vel

# Output
outputname              {output.stem}
outputEnergies          500
restartfreq             1000
DCDfreq                 500

# NVT ensemble with heating
langevin                on
langevinDamping         {self.config.langevin_damping}
langevinTemp            {start_temp}
langevinHydrogen        off

# Temperature reassignment (heating)
reassignFreq            {reassign_freq}
reassignTemp            {start_temp}
reassignIncr            {temp_incr:.4f}
reassignHold            {target_temp}

# Run
run                     {steps}
{restraint_section}
'''
        
        output.write_text(config)
        self.log.info(f"Wrote heating config: {output}")
        return output
    
    def write_equilibration(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 100000,
        ensemble: str = "NPT",
        restraint_pdb: str | None = None,
    ) -> Path:
        """
        Write NAMD equilibration configuration.
        
        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Input coordinates (restart from heating)
        output : Path
            Output NAMD config file path
        steps : int
            Number of equilibration steps
        ensemble : str
            Ensemble type (NPT or NVT)
        restraint_pdb : str, optional
            PDB file with restraint forces
            
        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)
        
        box = self._get_box_from_inpcrd(coordinates)
        
        restraint_section = ""
        if restraint_pdb:
            restraint_section = self._get_restraint_config(restraint_pdb)
        
        barostat_section = ""
        if ensemble == "NPT":
            barostat_section = f'''
# Pressure control (NPT)
useGroupPressure        yes
useFlexibleCell         no
useConstantArea         no

langevinPiston          on
langevinPistonTarget    {self.config.pressure}
langevinPistonPeriod    100.0
langevinPistonDecay     50.0
langevinPistonTemp      {self.config.temperature}
'''
        
        config = f'''{self._get_common_config(topology, coordinates, box)}
# Input (from previous stage)
bincoordinates          {output.stem.replace('_eq', '_heat')}.coor
binvelocities           {output.stem.replace('_eq', '_heat')}.vel
extendedSystem          {output.stem.replace('_eq', '_heat')}.xsc

# Output
outputname              {output.stem}
outputEnergies          1000
restartfreq             5000
DCDfreq                 1000
XSTfreq                 1000

# Temperature control
langevin                on
langevinDamping         {self.config.langevin_damping}
langevinTemp            {self.config.temperature}
langevinHydrogen        off
{barostat_section}
# Run
run                     {steps}
{restraint_section}
'''
        
        output.write_text(config)
        self.log.info(f"Wrote equilibration config: {output}")
        return output
    
    def write_production(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 500000,
        ensemble: str = "NVT",
        dcd_freq: int = 500,
    ) -> Path:
        """
        Write NAMD production MD configuration.
        
        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Input coordinates (restart from equilibration)
        output : Path
            Output NAMD config file path
        steps : int
            Number of production steps
        ensemble : str
            Ensemble type (NPT or NVT)
        dcd_freq : int
            DCD trajectory save frequency
            
        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)
        
        box = self._get_box_from_inpcrd(coordinates)
        
        barostat_section = ""
        if ensemble == "NPT":
            barostat_section = f'''
# Pressure control (NPT)
useGroupPressure        yes
useFlexibleCell         no
useConstantArea         no

langevinPiston          on
langevinPistonTarget    {self.config.pressure}
langevinPistonPeriod    100.0
langevinPistonDecay     50.0
langevinPistonTemp      {self.config.temperature}
'''
        
        config = f'''{self._get_common_config(topology, coordinates, box)}
# Input (from equilibration)
bincoordinates          {output.stem.replace('_prod', '_eq')}.coor
binvelocities           {output.stem.replace('_eq', '_heat')}.vel
extendedSystem          {output.stem.replace('_prod', '_eq')}.xsc

# Output
outputname              {output.stem}
outputEnergies          5000
restartfreq             10000
DCDfreq                 {dcd_freq}
XSTfreq                 5000

# Temperature control
langevin                on
langevinDamping         {self.config.langevin_damping}
langevinTemp            {self.config.temperature}
langevinHydrogen        off
{barostat_section}
# Run
run                     {steps}
'''
        
        output.write_text(config)
        self.log.info(f"Wrote production config: {output}")
        return output
    
    def write_replica_inputs(
        self,
        replica,
        output_dir: str | Path | None = None,
    ) -> list[Path]:
        """
        Write all NAMD input files for a replica.
        
        Parameters
        ----------
        replica : Replica
            Replica to generate inputs for
        output_dir : Path, optional
            Output directory (defaults to replica.path)
            
        Returns
        -------
        list[Path]
            List of generated config file paths
        """
        output_dir = Path(output_dir) if output_dir else replica.path
        output_dir.mkdir(parents=True, exist_ok=True)
        
        topology = replica.path / replica.topology
        coordinates = replica.path / replica.coordinates
        
        configs = []
        
        # Create restraint PDB if needed
        restraint_pdb = str(output_dir / "restraints.pdb")
        # Note: In full implementation, would create PDB with B-factors
        
        # Minimization
        configs.append(self.write_minimization(
            topology, coordinates,
            output_dir / "min.namd",
            restraint_pdb=restraint_pdb,
        ))
        
        # Heating
        configs.append(self.write_heating(
            topology, coordinates,
            output_dir / "heat.namd",
            restraint_pdb=restraint_pdb,
        ))
        
        # Equilibration (NPT)
        configs.append(self.write_equilibration(
            topology, coordinates,
            output_dir / "eq.namd",
            ensemble="NPT",
            restraint_pdb=restraint_pdb,
        ))
        
        # Production (NVT)
        configs.append(self.write_production(
            topology, coordinates,
            output_dir / "prod.namd",
            ensemble="NVT",
        ))
        
        # Write run script
        run_script = output_dir / "run_namd.sh"
        run_script.write_text(f'''#!/bin/bash
# NAMD run script - Generated by pyMDMix

NAMD="namd2"

echo "Running minimization..."
$NAMD min.namd > min.log

echo "Running heating..."
$NAMD heat.namd > heat.log

echo "Running equilibration..."
$NAMD eq.namd > eq.log

echo "Running production..."
$NAMD prod.namd > prod.log

echo "Done!"
''')
        run_script.chmod(0o755)
        configs.append(run_script)
        
        return configs
