"""
NAMD Engine Interface
=====================

Generate NAMD configuration files for MDMix workflows.

Examples
--------
>>> from pymdmix.engines.namd import NAMDEngine
>>> engine = NAMDEngine()
>>> engine.write_minimization("system.prmtop", "system.inpcrd", "min.namd")
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)


@dataclass
class NAMDConfig:
    """
    NAMD simulation configuration.

    Attributes
    ----------
    cutoff : float
        Nonbonded cutoff in Angstroms
    switch_dist : float
        Switching distance in Angstroms
    pairlist_dist : float
        Pairlist distance in Angstroms
    timestep : float
        Integration timestep in femtoseconds
    temperature : float
        Temperature in Kelvin
    pressure : float
        Pressure in bar (for NPT)
    langevin_damping : float
        Langevin damping coefficient in 1/ps
    """

    cutoff: float = 9.0
    switch_dist: float = 7.5
    pairlist_dist: float = 13.5
    timestep: float = 2.0
    temperature: float = 300.0
    pressure: float = 1.01325
    langevin_damping: float = 1.0

    # PME settings
    pme_grid_spacing: float = 1.0

    # Restraint settings
    restraint_weight: float = 10.0  # kcal/mol/Å²
    restraint_mask: str | None = None


class NAMDEngine:
    """
    NAMD simulation engine for MDMix.

    Generates NAMD configuration files for running simulations
    with Amber topology files.
    """

    def __init__(self, config: NAMDConfig | None = None):
        self.config = config or NAMDConfig()
        self.log = logging.getLogger(self.__class__.__name__)

    def _get_box_from_inpcrd(self, inpcrd_path: Path) -> tuple[float, float, float]:
        """Read box dimensions from Amber inpcrd file."""
        with open(inpcrd_path) as f:
            lines = f.readlines()

        # Box is in last line for periodic systems
        box_line = lines[-1].strip()
        parts = box_line.split()

        if len(parts) >= 3:
            try:
                return (float(parts[0]), float(parts[1]), float(parts[2]))
            except ValueError:
                pass

        # Default box if not found
        return (50.0, 50.0, 50.0)

    def _get_common_config(self, topology: Path, coordinates: Path, box: tuple) -> str:
        """Generate common NAMD configuration section."""
        return f"""# NAMD Configuration - Generated by pyMDMix
# Force field
amber                   on
parmfile                {topology}
ambercoor               {coordinates}
readexclusions          yes
exclude                 scaled1-4
1-4scaling              0.833333

# Periodic boundary conditions
cellBasisVector1        {box[0]:.3f} 0.0 0.0
cellBasisVector2        0.0 {box[1]:.3f} 0.0
cellBasisVector3        0.0 0.0 {box[2]:.3f}
cellOrigin              {box[0] / 2:.3f} {box[1] / 2:.3f} {box[2] / 2:.3f}

wrapAll                 on
wrapNearest             on

# Nonbonded
cutoff                  {self.config.cutoff}
switching               on
switchdist              {self.config.switch_dist}
pairlistdist            {self.config.pairlist_dist}

# PME
PME                     on
PMEGridSpacing          {self.config.pme_grid_spacing}

# Rigid bonds
rigidBonds              all
rigidTolerance          0.00001

# Timestep
timestep                {self.config.timestep}
"""

    def _get_restraint_config(self, pdb_path: str) -> str:
        """Generate restraint configuration."""
        return f"""
# Restraints
constraints             on
consref                 {pdb_path}
conskfile               {pdb_path}
conskcol                B
constraintScaling       {self.config.restraint_weight}
"""

    def write_minimization(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 5000,
        restraint_pdb: str | None = None,
    ) -> Path:
        """
        Write NAMD minimization configuration.

        Parameters
        ----------
        topology : Path
            Amber topology file (.prmtop)
        coordinates : Path
            Amber coordinates file (.inpcrd)
        output : Path
            Output NAMD config file path
        steps : int
            Number of minimization steps
        restraint_pdb : str, optional
            PDB file with restraint forces in B-factor column

        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)

        box = self._get_box_from_inpcrd(coordinates)

        restraint_section = ""
        if restraint_pdb:
            restraint_section = self._get_restraint_config(restraint_pdb)

        config = f"""{self._get_common_config(topology, coordinates, box)}
# Output
outputname              {output.stem}
outputEnergies          100
restartfreq             1000
DCDfreq                 0

# Minimization
minimization            on
minimize                {steps}
{restraint_section}
"""

        output.write_text(config)
        self.log.info(f"Wrote minimization config: {output}")
        return output

    def write_heating(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 50000,
        start_temp: float = 0.0,
        target_temp: float | None = None,
        restraint_pdb: str | None = None,
    ) -> Path:
        """
        Write NAMD heating/equilibration configuration.

        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Input coordinates (restart from minimization)
        output : Path
            Output NAMD config file path
        steps : int
            Number of equilibration steps
        start_temp : float
            Starting temperature in K
        target_temp : float, optional
            Target temperature (defaults to config.temperature)
        restraint_pdb : str, optional
            PDB file with restraint forces

        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)

        target_temp = target_temp or self.config.temperature
        box = self._get_box_from_inpcrd(coordinates)

        restraint_section = ""
        if restraint_pdb:
            restraint_section = self._get_restraint_config(restraint_pdb)

        # Calculate temperature increment
        reassign_freq = 100
        n_reassigns = steps // reassign_freq
        temp_incr = (target_temp - start_temp) / max(n_reassigns, 1)

        config = f"""{self._get_common_config(topology, coordinates, box)}
# Input
bincoordinates          {output.stem.replace("_heat", "_min")}.coor
binvelocities           {output.stem.replace("_heat", "_min")}.vel

# Output
outputname              {output.stem}
outputEnergies          500
restartfreq             1000
DCDfreq                 500

# NVT ensemble with heating
langevin                on
langevinDamping         {self.config.langevin_damping}
langevinTemp            {start_temp}
langevinHydrogen        off

# Temperature reassignment (heating)
reassignFreq            {reassign_freq}
reassignTemp            {start_temp}
reassignIncr            {temp_incr:.4f}
reassignHold            {target_temp}

# Run
run                     {steps}
{restraint_section}
"""

        output.write_text(config)
        self.log.info(f"Wrote heating config: {output}")
        return output

    def write_equilibration(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 100000,
        ensemble: str = "NPT",
        restraint_pdb: str | None = None,
    ) -> Path:
        """
        Write NAMD equilibration configuration.

        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Input coordinates (restart from heating)
        output : Path
            Output NAMD config file path
        steps : int
            Number of equilibration steps
        ensemble : str
            Ensemble type (NPT or NVT)
        restraint_pdb : str, optional
            PDB file with restraint forces

        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)

        box = self._get_box_from_inpcrd(coordinates)

        restraint_section = ""
        if restraint_pdb:
            restraint_section = self._get_restraint_config(restraint_pdb)

        barostat_section = ""
        if ensemble == "NPT":
            barostat_section = f"""
# Pressure control (NPT)
useGroupPressure        yes
useFlexibleCell         no
useConstantArea         no

langevinPiston          on
langevinPistonTarget    {self.config.pressure}
langevinPistonPeriod    100.0
langevinPistonDecay     50.0
langevinPistonTemp      {self.config.temperature}
"""

        config = f"""{self._get_common_config(topology, coordinates, box)}
# Input (from previous stage)
bincoordinates          {output.stem.replace("_eq", "_heat")}.coor
binvelocities           {output.stem.replace("_eq", "_heat")}.vel
extendedSystem          {output.stem.replace("_eq", "_heat")}.xsc

# Output
outputname              {output.stem}
outputEnergies          1000
restartfreq             5000
DCDfreq                 1000
XSTfreq                 1000

# Temperature control
langevin                on
langevinDamping         {self.config.langevin_damping}
langevinTemp            {self.config.temperature}
langevinHydrogen        off
{barostat_section}
# Run
run                     {steps}
{restraint_section}
"""

        output.write_text(config)
        self.log.info(f"Wrote equilibration config: {output}")
        return output

    def write_production(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 500000,
        ensemble: str = "NVT",
        dcd_freq: int = 500,
    ) -> Path:
        """
        Write NAMD production MD configuration.

        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Input coordinates (restart from equilibration)
        output : Path
            Output NAMD config file path
        steps : int
            Number of production steps
        ensemble : str
            Ensemble type (NPT or NVT)
        dcd_freq : int
            DCD trajectory save frequency

        Returns
        -------
        Path
            Path to generated config
        """
        topology = Path(topology)
        coordinates = Path(coordinates)
        output = Path(output)

        box = self._get_box_from_inpcrd(coordinates)

        barostat_section = ""
        if ensemble == "NPT":
            barostat_section = f"""
# Pressure control (NPT)
useGroupPressure        yes
useFlexibleCell         no
useConstantArea         no

langevinPiston          on
langevinPistonTarget    {self.config.pressure}
langevinPistonPeriod    100.0
langevinPistonDecay     50.0
langevinPistonTemp      {self.config.temperature}
"""

        config = f"""{self._get_common_config(topology, coordinates, box)}
# Input (from equilibration)
bincoordinates          {output.stem.replace("_prod", "_eq")}.coor
binvelocities           {output.stem.replace("_eq", "_heat")}.vel
extendedSystem          {output.stem.replace("_prod", "_eq")}.xsc

# Output
outputname              {output.stem}
outputEnergies          5000
restartfreq             10000
DCDfreq                 {dcd_freq}
XSTfreq                 5000

# Temperature control
langevin                on
langevinDamping         {self.config.langevin_damping}
langevinTemp            {self.config.temperature}
langevinHydrogen        off
{barostat_section}
# Run
run                     {steps}
"""

        output.write_text(config)
        self.log.info(f"Wrote production config: {output}")
        return output

    def write_replica_inputs(
        self,
        replica,
        output_dir: str | Path | None = None,
    ) -> list[Path]:
        """
        Write all NAMD input files for a replica.

        Parameters
        ----------
        replica : Replica
            Replica to generate inputs for
        output_dir : Path, optional
            Output directory (defaults to replica.path)

        Returns
        -------
        list[Path]
            List of generated config file paths
        """
        output_dir = Path(output_dir) if output_dir else replica.path
        output_dir.mkdir(parents=True, exist_ok=True)

        topology = replica.path / replica.topology
        coordinates = replica.path / replica.coordinates

        configs = []

        # Create restraint PDB if needed
        restraint_pdb = str(output_dir / "restraints.pdb")
        # Note: In full implementation, would create PDB with B-factors

        # Minimization
        configs.append(
            self.write_minimization(
                topology,
                coordinates,
                output_dir / "min.namd",
                restraint_pdb=restraint_pdb,
            )
        )

        # Heating
        configs.append(
            self.write_heating(
                topology,
                coordinates,
                output_dir / "heat.namd",
                restraint_pdb=restraint_pdb,
            )
        )

        # Equilibration (NPT)
        configs.append(
            self.write_equilibration(
                topology,
                coordinates,
                output_dir / "eq.namd",
                ensemble="NPT",
                restraint_pdb=restraint_pdb,
            )
        )

        # Production (NVT)
        configs.append(
            self.write_production(
                topology,
                coordinates,
                output_dir / "prod.namd",
                ensemble="NVT",
            )
        )

        # Write run script
        run_script = output_dir / "run_namd.sh"
        run_script.write_text("""#!/bin/bash
# NAMD run script - Generated by pyMDMix

NAMD="namd2"

echo "Running minimization..."
$NAMD min.namd > min.log

echo "Running heating..."
$NAMD heat.namd > heat.log

echo "Running equilibration..."
$NAMD eq.namd > eq.log

echo "Running production..."
$NAMD prod.namd > prod.log

echo "Done!"
""")
        run_script.chmod(0o755)
        configs.append(run_script)

        return configs


# =============================================================================
# NAMDWriter - Replica-level input file generation
# =============================================================================

# Completion string that NAMD writes at the end of a successful run
_NAMD_COMPLETE = "End of program"


class NAMDWriterError(Exception):
    """Error raised by NAMDWriter."""


class NAMDWriter:
    """
    Write NAMD input files for a :class:`~pymdmix.project.replica.Replica`.

    Mirrors :class:`~pymdmix.engines.amber.AmberWriter` in interface.

    Examples
    --------
    >>> from pymdmix.engines.namd import NAMDWriter
    >>> writer = NAMDWriter(replica)
    >>> writer.write_replica_input()
    >>> writer.write_commands()
    """

    def __init__(self, replica) -> None:
        self.replica = replica
        self.engine = NAMDEngine(
            NAMDConfig(
                timestep=replica.settings.timestep if replica.settings else 2.0,
                temperature=replica.settings.temperature if replica.settings else 300.0,
            )
        )
        self.log = logging.getLogger(self.__class__.__name__)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_restraint_mask(self) -> str:
        """Return the Amber restraint mask string for this replica."""
        settings = self.replica.settings
        if not settings:
            return ""
        if settings.restraint_mask:
            return settings.restraint_mask
        mode = settings.restraint_mode.upper()
        if mode == "FREE":
            return ""
        if mode == "BB":
            return "@CA,C,N,O"
        if mode == "HA":
            return "!@H="
        return "@CA"

    def _write_restraint_pdb(self) -> Path | None:
        """
        Create *restraints.pdb* in the replica folder.

        Sets the B-factor column to ``restraint_force`` for atoms
        matching the restraint mask, and 0 for all others.

        Returns the path if written, ``None`` if no restraints are needed.
        """
        import parmed

        settings = self.replica.settings
        if not settings or settings.restraint_mode.upper() == "FREE":
            return None

        pdb_path = self.replica.pdb_path
        if pdb_path is None or not pdb_path.exists():
            self.log.warning("pdb_path not set/found; cannot write restraints.pdb")
            return None

        out_path = self.replica.path / "restraints.pdb"

        try:
            struct = parmed.load_file(str(pdb_path))
            force = settings.restraint_force

            # Identify restrained atoms
            mask_str = self._get_restraint_mask()
            if mask_str:
                amber_mask = parmed.amber.AmberMask(struct, mask_str)
                restrained = set(amber_mask.Selected())
            else:
                restrained = set()

            for i, atom in enumerate(struct.atoms):
                atom.bfactor = force if i in restrained else 0.0

            struct.save(str(out_path), overwrite=True)
            self.log.debug(f"Wrote restraints.pdb → {out_path}")
            return out_path

        except Exception as exc:
            self.log.warning(f"Could not write restraints.pdb: {exc}")
            return None

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def write_replica_input(self) -> None:
        """Write min, eq1, eq2, and per-step production .namd files."""
        replica = self.replica
        if not replica.path:
            raise NAMDWriterError("Replica path not set")

        settings = replica.settings
        if not settings:
            raise NAMDWriterError("Replica settings not configured")

        has_restraints = settings.has_restraints
        restraint_pdb: str | None = None

        if has_restraints:
            rp = self._write_restraint_pdb()
            restraint_pdb = str(rp) if rp else None

        top = replica.topology_path
        crd = replica.coordinates_path
        if top is None or crd is None:
            raise NAMDWriterError("Replica topology/coordinates not set")

        # ---- Minimization ------------------------------------------------
        min_path = replica.min_path
        if min_path:
            min_path.mkdir(exist_ok=True)
            self.engine.write_minimization(
                topology=top,
                coordinates=crd,
                output=min_path / "min.namd",
                steps=5000,
                restraint_pdb=restraint_pdb,
            )

        # ---- Equilibration -----------------------------------------------
        eq_path = replica.eq_path
        if eq_path:
            eq_path.mkdir(exist_ok=True)

            # eq1: NVT heating from 0 K → target temperature
            self.engine.write_heating(
                topology=top,
                coordinates=crd,
                output=eq_path / "eq1.namd",
                steps=50000,
                start_temp=0.0,
                target_temp=settings.temperature,
                restraint_pdb=restraint_pdb,
            )

            # eq2: NPT equilibration at target temperature
            self.engine.write_equilibration(
                topology=top,
                coordinates=crd,
                output=eq_path / "eq2.namd",
                steps=100000,
                ensemble="NPT",
                restraint_pdb=restraint_pdb,
            )

        # ---- Production --------------------------------------------------
        md_path = replica.md_path
        if md_path:
            md_path.mkdir(exist_ok=True)
            for step in range(1, settings.n_traj_files + 1):
                step_name = replica.md_output_template.format(step=step, extension="").rstrip(".")
                self.engine.write_production(
                    topology=top,
                    coordinates=crd,
                    output=md_path / f"{step_name}.namd",
                    steps=settings.prod_steps,
                    ensemble="NVT",
                    dcd_freq=settings.traj_frequency,
                )

        self.log.info(f"Wrote NAMD input files for replica {replica.name}")

    def write_commands(self, output: Path | str = "COMMANDS.sh") -> None:
        """Write a shell script that runs all stages sequentially."""
        replica = self.replica
        if not replica.path:
            raise NAMDWriterError("Replica path not set")

        settings = replica.settings
        if not settings:
            raise NAMDWriterError("Replica settings not configured")

        namd_exe = "namd2"

        lines = [
            "#!/bin/bash",
            f"# Commands for replica {replica.name} (NAMD)",
            "",
            f"NAMD={namd_exe}",
            "",
            "# Minimization",
            f"cd {replica.min_folder}",
            "$NAMD min.namd > min.out",
            "cd ..",
            "",
            "# Equilibration",
            f"cd {replica.eq_folder}",
            "$NAMD eq1.namd > eq1.out",
            "$NAMD eq2.namd > eq2.out",
            "cd ..",
            "",
            "# Production",
            f"cd {replica.md_folder}",
        ]

        for step in range(1, settings.n_traj_files + 1):
            step_name = replica.md_output_template.format(step=step, extension="").rstrip(".")
            lines.append(f"$NAMD {step_name}.namd > {step_name}.out")

        lines.extend(["cd ..", ""])

        script = "\n".join(lines)
        script_path = replica.path / output
        script_path.write_text(script)
        script_path.chmod(0o755)

        self.log.info(f"Wrote NAMD commands script: {script_path}")


# =============================================================================
# NAMDChecker - verify simulation completion
# =============================================================================


class NAMDChecker:
    """
    Check NAMD simulation completion status.

    Mirrors :class:`~pymdmix.engines.amber.AmberChecker` in interface.

    Examples
    --------
    >>> checker = NAMDChecker(replica)
    >>> if checker.check_production([1, 2, 3]):
    ...     print("First 3 steps complete")
    """

    def __init__(self, replica, warn: bool = True) -> None:
        self.replica = replica
        self.warn = warn
        self.log = logging.getLogger(self.__class__.__name__)

    def _read_out(self, path: Path) -> str | None:
        """Return file content or None if the file is missing."""
        if path.exists():
            return path.read_text()
        return None

    def check_minimization(self) -> bool:
        """Return ``True`` if minimization completed successfully."""
        min_path = self.replica.min_path
        if not min_path or not min_path.exists():
            if self.warn:
                self.log.warning(f"Minimization folder not found: {min_path}")
            return False

        out = self._read_out(min_path / "min.out")
        if out is None:
            if self.warn:
                self.log.warning("Minimization output file not found")
            return False

        if _NAMD_COMPLETE in out:
            return True

        if self.warn:
            self.log.warning("Minimization not complete (no NAMD completion marker)")
        return False

    def check_equilibration(
        self,
        step_selection: list[int] | None = None,
    ) -> bool:
        """
        Return ``True`` if all selected equilibration steps completed.

        Parameters
        ----------
        step_selection : list[int] | None
            Steps to check (1-based). Defaults to [1, 2].
        """
        eq_path = self.replica.eq_path
        if not eq_path or not eq_path.exists():
            if self.warn:
                self.log.warning(f"Equilibration folder not found: {eq_path}")
            return False

        steps = step_selection if step_selection is not None else [1, 2]

        for step in steps:
            out = self._read_out(eq_path / f"eq{step}.out")
            if out is None:
                if self.warn:
                    self.log.warning(f"Equilibration step {step} output not found")
                return False
            if _NAMD_COMPLETE not in out:
                if self.warn:
                    self.log.warning(f"Equilibration step {step} not complete")
                return False

        return True

    def check_production(
        self,
        step_selection: list[int] | None = None,
    ) -> bool:
        """
        Return ``True`` if all selected production steps completed.

        Parameters
        ----------
        step_selection : list[int] | None
            Steps to check (1-based). Defaults to all expected steps.
        """
        md_path = self.replica.md_path
        if not md_path or not md_path.exists():
            if self.warn:
                self.log.warning(f"Production folder not found: {md_path}")
            return False

        if step_selection is None:
            settings = self.replica.settings
            step_selection = list(range(1, settings.n_traj_files + 1)) if settings else [1]

        for step in step_selection:
            step_name = self.replica.md_output_template.format(step=step, extension="").rstrip(".")
            out = self._read_out(md_path / f"{step_name}.out")
            if out is None:
                if self.warn:
                    self.log.warning(f"Production step {step} output not found")
                return False
            if _NAMD_COMPLETE not in out:
                if self.warn:
                    self.log.warning(f"Production step {step} not complete")
                return False

        return True

    def get_sim_volume(self, step: int = 1) -> float | None:
        """
        Parse box volume from the NAMD extended-system file (.xsc).

        The .xsc format stores the three box vectors; for an orthorhombic
        box only the diagonal elements are non-zero.

        Parameters
        ----------
        step : int
            Production step whose .xsc file to read.

        Returns
        -------
        float | None
            Box volume in Å³, or ``None`` if the file cannot be parsed.
        """
        import numpy as np

        md_path = self.replica.md_path
        if not md_path:
            return None

        step_name = self.replica.md_output_template.format(step=step, extension="").rstrip(".")
        xsc_path = md_path / f"{step_name}.xsc"

        if not xsc_path.exists():
            self.log.warning(f"XSC file not found: {xsc_path}")
            return None

        try:
            # XSC format: first two lines are comments; third line contains
            # step  a1x a1y a1z  a2x a2y a2z  a3x a3y a3z  ox oy oz  ...
            lines = xsc_path.read_text().splitlines()
            data_lines = [line for line in lines if not line.startswith("#") and line.strip()]
            if not data_lines:
                return None

            values = list(map(float, data_lines[-1].split()))
            # Columns 1-3: first vector, 4-6: second, 7-9: third
            vec_a = np.array(values[1:4])
            vec_b = np.array(values[4:7])
            vec_c = np.array(values[7:10])

            # Volume = |a · (b × c)|
            vol = abs(np.dot(vec_a, np.cross(vec_b, vec_c)))
            return float(vol)

        except Exception as exc:
            self.log.warning(f"Could not parse XSC file {xsc_path}: {exc}")
            return None
