"""
OpenMM Engine Interface
=======================

Generate OpenMM simulation scripts for MDMix workflows.
Requires OpenMM to be installed separately.

Examples
--------
>>> from pymdmix.engines.openmm import OpenMMEngine
>>> engine = OpenMMEngine()
>>> engine.write_minimization("system.prmtop", "system.inpcrd", "min.py")
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

import numpy as np

log = logging.getLogger(__name__)


@dataclass
class OpenMMConfig:
    """
    OpenMM simulation configuration.
    
    Attributes
    ----------
    platform : str
        Compute platform (CUDA, OpenCL, CPU, Reference)
    precision : str
        Floating point precision (mixed, single, double)
    device_index : int
        GPU device index
    nonbonded_cutoff : float
        Nonbonded cutoff in Angstroms
    nonbonded_method : str
        Nonbonded method (PME, CutoffPeriodic, NoCutoff)
    constraints : str
        Constraint method (HBonds, AllBonds, None)
    timestep : float
        Integration timestep in femtoseconds
    temperature : float
        Temperature in Kelvin
    pressure : float
        Pressure in bar (for NPT)
    friction : float
        Langevin friction coefficient in 1/ps
    """
    platform: str = "CUDA"
    precision: str = "mixed"
    device_index: int = 0
    nonbonded_cutoff: float = 9.0
    nonbonded_method: str = "PME"
    constraints: str = "HBonds"
    timestep: float = 2.0
    temperature: float = 300.0
    pressure: float = 1.0
    friction: float = 1.0
    
    # Restraint settings
    restraint_weight: float = 10.0  # kcal/mol/Å²
    restraint_mask: str | None = None


@dataclass
class OpenMMInput:
    """
    OpenMM input file paths.
    
    Attributes
    ----------
    topology : Path
        Amber topology file (.prmtop)
    coordinates : Path
        Amber coordinates file (.inpcrd/.rst7)
    output_prefix : str
        Prefix for output files
    """
    topology: Path
    coordinates: Path
    output_prefix: str = "openmm"
    restart: Path | None = None


class OpenMMEngine:
    """
    OpenMM simulation engine for MDMix.
    
    Generates Python scripts for running OpenMM simulations
    with Amber topology files.
    """
    
    def __init__(self, config: OpenMMConfig | None = None):
        self.config = config or OpenMMConfig()
        self.log = logging.getLogger(self.__class__.__name__)
    
    def write_minimization(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 5000,
        restraint_mask: str | None = None,
    ) -> Path:
        """
        Write OpenMM minimization script.
        
        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Amber coordinates file
        output : Path
            Output Python script path
        steps : int
            Maximum minimization steps
        restraint_mask : str, optional
            Atom mask for positional restraints
            
        Returns
        -------
        Path
            Path to generated script
        """
        output = Path(output)
        
        restraint_code = ""
        if restraint_mask:
            restraint_code = self._get_restraint_code(restraint_mask)
        
        script = f'''#!/usr/bin/env python
"""OpenMM Minimization Script - Generated by pyMDMix"""
import sys
try:
    import openmm as mm
    import openmm.app as app
    import openmm.unit as u
except ImportError:
    import simtk.openmm as mm
    import simtk.openmm.app as app
    import simtk.unit as u

# Configuration
PLATFORM = "{self.config.platform}"
PRECISION = "{self.config.precision}"
DEVICE = "{self.config.device_index}"
CUTOFF = {self.config.nonbonded_cutoff} * u.angstrom
MAX_STEPS = {steps}

# Files
prmtop_file = "{topology}"
inpcrd_file = "{coordinates}"
output_prefix = "{output.stem}"

# Setup platform
platform = mm.Platform.getPlatformByName(PLATFORM)
properties = {{"Precision": PRECISION}}
if PLATFORM == "CUDA":
    properties["DeviceIndex"] = str(DEVICE)

# Load topology and coordinates
prmtop = app.AmberPrmtopFile(prmtop_file)
inpcrd = app.AmberInpcrdFile(inpcrd_file)

# Create system
system = prmtop.createSystem(
    nonbondedMethod=app.PME,
    nonbondedCutoff=CUTOFF,
    constraints=app.HBonds,
)

{restraint_code}

# Integrator (not used in minimization but required)
integrator = mm.VerletIntegrator(1.0 * u.femtosecond)

# Create simulation
simulation = app.Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.context.setPositions(inpcrd.positions)

if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

# Report initial energy
state = simulation.context.getState(getEnergy=True)
print(f"Initial energy: {{state.getPotentialEnergy()}}")

# Minimize
print(f"Running minimization (max {{MAX_STEPS}} steps)...")
simulation.minimizeEnergy(maxIterations=MAX_STEPS)

# Report final energy
state = simulation.context.getState(getEnergy=True, getPositions=True)
print(f"Final energy: {{state.getPotentialEnergy()}}")

# Save minimized coordinates
positions = state.getPositions()
with open(f"{{output_prefix}}.rst7", "w") as f:
    app.AmberInpcrdFile.writeFile(simulation.topology, positions, f)

print(f"Minimization complete. Output: {{output_prefix}}.rst7")
'''
        
        output.write_text(script)
        output.chmod(0o755)
        self.log.info(f"Wrote minimization script: {output}")
        return output
    
    def write_equilibration(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 50000,
        ensemble: str = "NPT",
        restraint_mask: str | None = None,
    ) -> Path:
        """
        Write OpenMM equilibration script.
        
        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Amber coordinates/restart file
        output : Path
            Output Python script path
        steps : int
            Number of equilibration steps
        ensemble : str
            Ensemble type (NPT or NVT)
        restraint_mask : str, optional
            Atom mask for positional restraints
            
        Returns
        -------
        Path
            Path to generated script
        """
        output = Path(output)
        
        restraint_code = ""
        if restraint_mask:
            restraint_code = self._get_restraint_code(restraint_mask)
        
        barostat_code = ""
        if ensemble == "NPT":
            barostat_code = f'''
# Add barostat for NPT
barostat = mm.MonteCarloBarostat({self.config.pressure} * u.bar, {self.config.temperature} * u.kelvin)
system.addForce(barostat)
'''
        
        script = f'''#!/usr/bin/env python
"""OpenMM Equilibration Script ({ensemble}) - Generated by pyMDMix"""
import sys
try:
    import openmm as mm
    import openmm.app as app
    import openmm.unit as u
except ImportError:
    import simtk.openmm as mm
    import simtk.openmm.app as app
    import simtk.unit as u

# Configuration
PLATFORM = "{self.config.platform}"
PRECISION = "{self.config.precision}"
DEVICE = "{self.config.device_index}"
CUTOFF = {self.config.nonbonded_cutoff} * u.angstrom
TIMESTEP = {self.config.timestep} * u.femtosecond
TEMPERATURE = {self.config.temperature} * u.kelvin
FRICTION = {self.config.friction} / u.picosecond
STEPS = {steps}
REPORT_FREQ = 1000

# Files
prmtop_file = "{topology}"
inpcrd_file = "{coordinates}"
output_prefix = "{output.stem}"

# Setup platform
platform = mm.Platform.getPlatformByName(PLATFORM)
properties = {{"Precision": PRECISION}}
if PLATFORM == "CUDA":
    properties["DeviceIndex"] = str(DEVICE)

# Load topology and coordinates
prmtop = app.AmberPrmtopFile(prmtop_file)
inpcrd = app.AmberInpcrdFile(inpcrd_file)

# Create system
system = prmtop.createSystem(
    nonbondedMethod=app.PME,
    nonbondedCutoff=CUTOFF,
    constraints=app.HBonds,
)

{restraint_code}
{barostat_code}

# Langevin integrator
integrator = mm.LangevinMiddleIntegrator(TEMPERATURE, FRICTION, TIMESTEP)

# Create simulation
simulation = app.Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.context.setPositions(inpcrd.positions)

if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

# Set velocities
simulation.context.setVelocitiesToTemperature(TEMPERATURE)

# Reporters
simulation.reporters.append(
    app.StateDataReporter(
        f"{{output_prefix}}.log", REPORT_FREQ,
        step=True, time=True, potentialEnergy=True, kineticEnergy=True,
        temperature=True, volume=True, density=True,
    )
)
simulation.reporters.append(
    app.CheckpointReporter(f"{{output_prefix}}.chk", REPORT_FREQ * 10)
)

# Run equilibration
print(f"Running {ensemble} equilibration ({{STEPS}} steps)...")
simulation.step(STEPS)

# Save final state
state = simulation.context.getState(getPositions=True, getVelocities=True)
positions = state.getPositions()
velocities = state.getVelocities()

with open(f"{{output_prefix}}.rst7", "w") as f:
    app.AmberInpcrdFile.writeFile(simulation.topology, positions, f)

simulation.saveCheckpoint(f"{{output_prefix}}_final.chk")

print(f"Equilibration complete. Output: {{output_prefix}}.rst7")
'''
        
        output.write_text(script)
        output.chmod(0o755)
        self.log.info(f"Wrote equilibration script: {output}")
        return output
    
    def write_production(
        self,
        topology: str | Path,
        coordinates: str | Path,
        output: str | Path,
        steps: int = 500000,
        ensemble: str = "NVT",
        trajectory_freq: int = 500,
    ) -> Path:
        """
        Write OpenMM production MD script.
        
        Parameters
        ----------
        topology : Path
            Amber topology file
        coordinates : Path
            Amber coordinates/restart file
        output : Path
            Output Python script path
        steps : int
            Number of production steps
        ensemble : str
            Ensemble type (NPT or NVT)
        trajectory_freq : int
            Trajectory save frequency
            
        Returns
        -------
        Path
            Path to generated script
        """
        output = Path(output)
        
        barostat_code = ""
        if ensemble == "NPT":
            barostat_code = f'''
# Add barostat for NPT
barostat = mm.MonteCarloBarostat({self.config.pressure} * u.bar, {self.config.temperature} * u.kelvin)
system.addForce(barostat)
'''
        
        script = f'''#!/usr/bin/env python
"""OpenMM Production MD Script ({ensemble}) - Generated by pyMDMix"""
import sys
try:
    import openmm as mm
    import openmm.app as app
    import openmm.unit as u
except ImportError:
    import simtk.openmm as mm
    import simtk.openmm.app as app
    import simtk.unit as u

# Configuration
PLATFORM = "{self.config.platform}"
PRECISION = "{self.config.precision}"
DEVICE = "{self.config.device_index}"
CUTOFF = {self.config.nonbonded_cutoff} * u.angstrom
TIMESTEP = {self.config.timestep} * u.femtosecond
TEMPERATURE = {self.config.temperature} * u.kelvin
FRICTION = {self.config.friction} / u.picosecond
STEPS = {steps}
TRAJ_FREQ = {trajectory_freq}
LOG_FREQ = 1000

# Files
prmtop_file = "{topology}"
inpcrd_file = "{coordinates}"
output_prefix = "{output.stem}"

# Setup platform
platform = mm.Platform.getPlatformByName(PLATFORM)
properties = {{"Precision": PRECISION}}
if PLATFORM == "CUDA":
    properties["DeviceIndex"] = str(DEVICE)

# Load topology and coordinates
prmtop = app.AmberPrmtopFile(prmtop_file)
inpcrd = app.AmberInpcrdFile(inpcrd_file)

# Create system
system = prmtop.createSystem(
    nonbondedMethod=app.PME,
    nonbondedCutoff=CUTOFF,
    constraints=app.HBonds,
)
{barostat_code}

# Langevin integrator
integrator = mm.LangevinMiddleIntegrator(TEMPERATURE, FRICTION, TIMESTEP)

# Create simulation
simulation = app.Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.context.setPositions(inpcrd.positions)

if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

# Set velocities
simulation.context.setVelocitiesToTemperature(TEMPERATURE)

# Reporters
simulation.reporters.append(
    app.StateDataReporter(
        f"{{output_prefix}}.log", LOG_FREQ,
        step=True, time=True, potentialEnergy=True, kineticEnergy=True,
        temperature=True, volume=True, density=True, speed=True,
    )
)
simulation.reporters.append(
    app.DCDReporter(f"{{output_prefix}}.dcd", TRAJ_FREQ)
)
simulation.reporters.append(
    app.CheckpointReporter(f"{{output_prefix}}.chk", LOG_FREQ * 10)
)

# Run production
print(f"Running {ensemble} production MD ({{STEPS}} steps)...")
print(f"Trajectory saved every {{TRAJ_FREQ}} steps to {{output_prefix}}.dcd")

simulation.step(STEPS)

# Save final state
state = simulation.context.getState(getPositions=True, getVelocities=True)
positions = state.getPositions()

with open(f"{{output_prefix}}.rst7", "w") as f:
    app.AmberInpcrdFile.writeFile(simulation.topology, positions, f)

print(f"Production complete. Trajectory: {{output_prefix}}.dcd")
'''
        
        output.write_text(script)
        output.chmod(0o755)
        self.log.info(f"Wrote production script: {output}")
        return output
    
    def _get_restraint_code(self, mask: str) -> str:
        """Generate code for positional restraints."""
        weight = self.config.restraint_weight
        return f'''
# Add positional restraints
# Mask: {mask}
restraint_force = mm.CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
restraint_force.addGlobalParameter("k", {weight} * u.kilocalories_per_mole / u.angstrom**2)
restraint_force.addPerParticleParameter("x0")
restraint_force.addPerParticleParameter("y0")
restraint_force.addPerParticleParameter("z0")

# Apply to backbone atoms (simplified - full mask parsing would need parmed)
for atom in prmtop.topology.atoms():
    if atom.name in ["CA", "C", "N", "O"]:
        pos = inpcrd.positions[atom.index]
        restraint_force.addParticle(atom.index, pos.value_in_unit(u.nanometer))

system.addForce(restraint_force)
'''
    
    def write_replica_inputs(
        self,
        replica,
        output_dir: str | Path | None = None,
    ) -> list[Path]:
        """
        Write all input scripts for a replica.
        
        Parameters
        ----------
        replica : Replica
            Replica to generate inputs for
        output_dir : Path, optional
            Output directory (defaults to replica.path)
            
        Returns
        -------
        list[Path]
            List of generated script paths
        """
        output_dir = Path(output_dir) if output_dir else replica.path
        output_dir.mkdir(parents=True, exist_ok=True)
        
        topology = replica.path / replica.topology
        coordinates = replica.path / replica.coordinates
        
        scripts = []
        
        # Minimization
        scripts.append(self.write_minimization(
            topology, coordinates,
            output_dir / "min.py",
            restraint_mask="backbone",
        ))
        
        # Equilibration (NPT with restraints)
        scripts.append(self.write_equilibration(
            topology, output_dir / "min.rst7",
            output_dir / "eq.py",
            ensemble="NPT",
            restraint_mask="backbone",
        ))
        
        # Production (NVT)
        scripts.append(self.write_production(
            topology, output_dir / "eq.rst7",
            output_dir / "prod.py",
            ensemble="NVT",
        ))
        
        return scripts


# ============================================================================
# OpenMM Utility Functions
# ============================================================================

def apply_harmonic_positional_restraints(
    system,
    force_constant: float,
    coordinates,
    atom_indices: Sequence[int],
) -> None:
    """
    Apply harmonic positional restraints to selected atoms.
    
    Mimics AMBER's restraint_wt functionality by adding a CustomExternalForce
    that restrains atoms to their initial positions.
    
    Parameters
    ----------
    system : openmm.System
        OpenMM system to modify (in place)
    force_constant : float
        Force constant in kcal/(mol·Å²)
    coordinates : openmm.app.AmberInpcrdFile or similar
        Coordinate file with getPositions() method
    atom_indices : Sequence[int]
        Indices of atoms to restrain
        
    Examples
    --------
    >>> import openmm.app as app
    >>> prmtop = app.AmberPrmtopFile("system.prmtop")
    >>> inpcrd = app.AmberInpcrdFile("system.inpcrd")
    >>> system = prmtop.createSystem()
    >>> # Restrain backbone atoms (indices 0-99)
    >>> apply_harmonic_positional_restraints(system, 10.0, inpcrd, range(100))
    
    Notes
    -----
    This function requires OpenMM to be installed. It will raise ImportError
    if OpenMM is not available.
    """
    try:
        import openmm as mm
        import openmm.unit as u
    except ImportError:
        import simtk.openmm as mm
        import simtk.unit as u
    
    # Convert force constant to OpenMM units
    k_kcal = u.Quantity(
        value=force_constant,
        unit=u.kilocalorie / (u.mole * u.angstrom * u.angstrom)
    )
    k_kj = k_kcal.in_units_of(
        u.kilojoule / (u.mole * u.nanometer * u.nanometer)
    )
    
    # Create restraint force
    force = mm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
    force.addGlobalParameter("k", k_kj)
    force.addPerParticleParameter("x0")
    force.addPerParticleParameter("y0")
    force.addPerParticleParameter("z0")
    
    # Add particles with their reference positions
    positions = coordinates.getPositions()
    for i in atom_indices:
        force.addParticle(i, positions[i])
    
    system.addForce(force)


def set_context_from_restart(simulation, restart_file) -> None:
    """
    Restore simulation context from an Amber restart file.
    
    Sets positions, velocities, and periodic box vectors from
    an Amber .rst7 restart file.
    
    Parameters
    ----------
    simulation : openmm.app.Simulation
        OpenMM simulation object
    restart_file : openmm.app.AmberInpcrdFile
        Loaded restart file with positions, velocities, and box vectors
        
    Examples
    --------
    >>> import openmm.app as app
    >>> prmtop = app.AmberPrmtopFile("system.prmtop")
    >>> system = prmtop.createSystem()
    >>> integrator = mm.LangevinIntegrator(300*u.kelvin, 1/u.ps, 2*u.fs)
    >>> simulation = app.Simulation(prmtop.topology, system, integrator)
    >>> restart = app.AmberInpcrdFile("restart.rst7")
    >>> set_context_from_restart(simulation, restart)
    
    Notes
    -----
    The restart file must contain velocities and box vectors for full
    restoration. If velocities are missing, only positions are set.
    """
    try:
        import openmm as mm
        import openmm.unit as u
    except ImportError:
        import simtk.openmm as mm
        import simtk.unit as u
    
    # Set positions
    simulation.context.setPositions(restart_file.positions)
    
    # Set velocities if available
    if hasattr(restart_file, 'velocities') and restart_file.velocities is not None:
        simulation.context.setVelocities(restart_file.velocities)
    
    # Set box vectors if available
    box_vectors = restart_file.getBoxVectors()
    if box_vectors is not None:
        x = mm.Vec3(
            box_vectors[0][0].value_in_unit(u.nanometers),
            box_vectors[0][1].value_in_unit(u.nanometers),
            box_vectors[0][2].value_in_unit(u.nanometers),
        )
        y = mm.Vec3(
            box_vectors[1][0].value_in_unit(u.nanometers),
            box_vectors[1][1].value_in_unit(u.nanometers),
            box_vectors[1][2].value_in_unit(u.nanometers),
        )
        z = mm.Vec3(
            box_vectors[2][0].value_in_unit(u.nanometers),
            box_vectors[2][1].value_in_unit(u.nanometers),
            box_vectors[2][2].value_in_unit(u.nanometers),
        )
        simulation.context.setPeriodicBoxVectors(x, y, z)


def get_backbone_indices(topology) -> list[int]:
    """
    Get indices of backbone atoms from OpenMM topology.
    
    Parameters
    ----------
    topology : openmm.app.Topology
        OpenMM topology object
        
    Returns
    -------
    list[int]
        Indices of backbone atoms (CA, C, N, O)
    """
    backbone_names = {"CA", "C", "N", "O"}
    indices = []
    for atom in topology.atoms():
        if atom.name in backbone_names:
            indices.append(atom.index)
    return indices


def get_heavy_atom_indices(topology) -> list[int]:
    """
    Get indices of heavy (non-hydrogen) atoms from OpenMM topology.
    
    Parameters
    ----------
    topology : openmm.app.Topology
        OpenMM topology object
        
    Returns
    -------
    list[int]
        Indices of heavy atoms
    """
    indices = []
    for atom in topology.atoms():
        if atom.element is not None and atom.element.mass > 1.5:
            indices.append(atom.index)
    return indices
