"""
Analysis Action Framework
=========================

Base classes and registry for analysis actions.
Provides plugin architecture for extensibility.

Examples
--------
>>> @register_action("my_analysis")
... class MyAction(Action):
...     def run(self, trajectory, **kwargs):
...         # Custom analysis logic
...         return ActionResult(success=True)

>>> action_cls = get_action("my_analysis")
>>> action = action_cls()
>>> result = action.run(trajectory)
"""

from __future__ import annotations

import logging
import time
from abc import ABC, abstractmethod
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, TypeVar

log = logging.getLogger(__name__)

# Type variable for action classes
T = TypeVar("T", bound="Action")


@dataclass
class ActionResult:
    """
    Result from an analysis action.

    Attributes
    ----------
    success : bool
        Whether the action completed successfully
    output_files : list[Path]
        Files generated by the action
    metadata : dict[str, Any]
        Additional result metadata
    error : str | None
        Error message if action failed
    elapsed_time : float
        Time taken in seconds
    """

    success: bool
    output_files: list[Path] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    error: str | None = None
    elapsed_time: float = 0.0

    def __repr__(self) -> str:
        status = "✓" if self.success else "✗"
        files = len(self.output_files)
        return f"ActionResult({status}, files={files}, time={self.elapsed_time:.2f}s)"


class Action(ABC):
    """
    Abstract base class for analysis actions.

    Subclass and implement `run()` to create custom analyses.
    Use `@register_action(name)` decorator to register.

    Attributes
    ----------
    name : str
        Action identifier (set by @register_action)
    description : str
        Human-readable description

    Examples
    --------
    >>> @register_action("density")
    ... class DensityAction(Action):
    ...     description = "Calculate probe density grids"
    ...
    ...     def run(self, trajectory, **kwargs):
    ...         # Implementation
    ...         return ActionResult(success=True)
    """

    name: str = "base"
    description: str = "Base action"

    def __init__(self):
        self.log = logging.getLogger(f"{__name__}.{self.__class__.__name__}")

    @abstractmethod
    def run(
        self,
        trajectory,
        reference=None,
        output_dir: Path | None = None,
        **kwargs,
    ) -> ActionResult:
        """
        Execute the analysis.

        Parameters
        ----------
        trajectory : TrajectoryReader
            Trajectory to analyze
        reference : parmed.Structure | None
            Reference structure for grid construction
        output_dir : Path | None
            Directory for output files
        **kwargs
            Action-specific parameters

        Returns
        -------
        ActionResult
            Result with success status and outputs
        """
        ...

    def validate(self, trajectory, **kwargs) -> list[str]:
        """
        Validate inputs before running.

        Returns
        -------
        list[str]
            List of validation errors (empty if valid)
        """
        errors = []
        if trajectory is None:
            errors.append("Trajectory is required")
        return errors

    def __call__(self, *args, **kwargs) -> ActionResult:
        """Run action with timing."""
        start = time.time()

        # Validate
        errors = self.validate(*args, **kwargs)
        if errors:
            return ActionResult(
                success=False,
                error=f"Validation failed: {'; '.join(errors)}",
                elapsed_time=time.time() - start,
            )

        # Run
        try:
            result = self.run(*args, **kwargs)
            result.elapsed_time = time.time() - start
            return result
        except Exception as e:
            self.log.exception(f"Action {self.name} failed")
            return ActionResult(
                success=False,
                error=str(e),
                elapsed_time=time.time() - start,
            )

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name!r})"


# Action registry
_ACTION_REGISTRY: dict[str, type[Action]] = {}


def register_action(name: str) -> Callable[[type[T]], type[T]]:
    """
    Decorator to register an action class.

    Parameters
    ----------
    name : str
        Unique action identifier

    Returns
    -------
    Callable
        Class decorator

    Examples
    --------
    >>> @register_action("my_action")
    ... class MyAction(Action):
    ...     pass
    """

    def decorator(cls: type[T]) -> type[T]:
        cls.name = name
        _ACTION_REGISTRY[name] = cls
        log.debug(f"Registered action: {name}")
        return cls

    return decorator


def get_action(name: str) -> type[Action] | None:
    """
    Get action class by name.

    Parameters
    ----------
    name : str
        Action identifier

    Returns
    -------
    type[Action] | None
        Action class if found
    """
    return _ACTION_REGISTRY.get(name)


def list_actions() -> list[str]:
    """
    List registered action names.

    Returns
    -------
    list[str]
        Sorted list of action names
    """
    return sorted(_ACTION_REGISTRY.keys())


def get_all_actions() -> dict[str, type[Action]]:
    """
    Get all registered actions.

    Returns
    -------
    dict[str, type[Action]]
        Name -> action class mapping
    """
    return _ACTION_REGISTRY.copy()


def run_action(
    name: str,
    trajectory,
    **kwargs,
) -> ActionResult:
    """
    Run an action by name.

    Parameters
    ----------
    name : str
        Action name
    trajectory : TrajectoryReader
        Trajectory to analyze
    **kwargs
        Action parameters

    Returns
    -------
    ActionResult
        Action result

    Raises
    ------
    ValueError
        If action not found
    """
    action_cls = get_action(name)
    if action_cls is None:
        raise ValueError(f"Unknown action: {name}. Available: {list_actions()}")

    action = action_cls()
    return action(trajectory, **kwargs)
